ALTER TABLE balances ALTER COLUMN token_mint TYPE VARCHAR(44);
ALTER TABLE transactions ALTER COLUMN token_mint TYPE VARCHAR(44);
ALTER TABLE payment_links ALTER COLUMN token_mint TYPE VARCHAR(44);
ALTER TABLE swap_history ALTER COLUMN input_mint TYPE VARCHAR(44);
ALTER TABLE swap_history ALTER COLUMN output_mint TYPE VARCHAR(44);
